2024-04-04 20:13:11,244 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Configure stats pid to 19412
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Loading settings from C:\Users\valer\.config\wandb\settings
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Loading settings from c:\Users\valer\Desktop\mmp_courses\ml\sem. 6\tasks\2.optimization\wandb\settings
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-04 20:13:11,245 INFO    MainThread:19412 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-04 20:13:11,246 INFO    MainThread:19412 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\valer\Desktop\mmp_courses\ml\sem. 6\tasks\2.optimization\wandb\run-20240404_201311-4rgvon0q\logs\debug.log
2024-04-04 20:13:11,246 INFO    MainThread:19412 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\valer\Desktop\mmp_courses\ml\sem. 6\tasks\2.optimization\wandb\run-20240404_201311-4rgvon0q\logs\debug-internal.log
2024-04-04 20:13:11,246 INFO    MainThread:19412 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002190CE98DF0>
2024-04-04 20:13:11,247 INFO    MainThread:19412 [wandb_init.py:init():566] calling init triggers
2024-04-04 20:13:11,247 INFO    MainThread:19412 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-04 20:13:11,248 INFO    MainThread:19412 [wandb_init.py:init():616] starting backend
2024-04-04 20:13:11,248 INFO    MainThread:19412 [wandb_init.py:init():620] setting up manager
2024-04-04 20:13:11,256 INFO    MainThread:19412 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-04 20:13:11,263 INFO    MainThread:19412 [wandb_init.py:init():628] backend started and connected
2024-04-04 20:13:11,285 INFO    MainThread:19412 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-04-04 20:13:11,286 INFO    MainThread:19412 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-04 20:13:11,286 INFO    MainThread:19412 [wandb_init.py:init():720] updated telemetry
2024-04-04 20:13:11,289 INFO    MainThread:19412 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-04-04 20:13:12,123 INFO    MainThread:19412 [wandb_run.py:_on_init():2262] communicating current version
2024-04-04 20:13:12,785 INFO    MainThread:19412 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-04-04 20:13:12,785 INFO    MainThread:19412 [wandb_init.py:init():804] starting run threads in backend
2024-04-04 20:13:29,015 INFO    MainThread:19412 [wandb_run.py:_console_start():2241] atexit reg
2024-04-04 20:13:29,015 INFO    MainThread:19412 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-04-04 20:13:29,015 INFO    MainThread:19412 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-04-04 20:13:29,015 INFO    MainThread:19412 [wandb_run.py:_redirect():2186] Redirects installed.
2024-04-04 20:13:29,017 INFO    MainThread:19412 [wandb_init.py:init():847] run started, returning control to user process
2024-04-04 20:14:32,520 INFO    MainThread:19412 [wandb_run.py:_finish():1970] finishing run valera_zykov/mmro_mmp/4rgvon0q
2024-04-04 20:14:32,521 INFO    MainThread:19412 [jupyter.py:save_history():445] not saving jupyter history
2024-04-04 20:14:32,521 INFO    MainThread:19412 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-04 20:14:32,521 INFO    MainThread:19412 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-04-04 20:14:32,521 INFO    MainThread:19412 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-04-04 20:14:32,522 INFO    MainThread:19412 [wandb_run.py:_restore():2193] restore
2024-04-04 20:14:32,522 INFO    MainThread:19412 [wandb_run.py:_restore():2199] restore done
2024-04-04 20:14:37,262 WARNING MsgRouterThr:19412 [router.py:message_loop():77] message_loop has been closed
2024-04-04 20:14:41,407 INFO    MainThread:19412 [wandb_run.py:_restore():2193] restore
2024-04-04 20:14:41,407 INFO    MainThread:19412 [wandb_run.py:_restore():2199] restore done
